# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.metadata_consistency import MetadataConsistency

class TestMetadataConsistency(unittest.TestCase):
    """MetadataConsistency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataConsistency(self):
        """Test MetadataConsistency"""
        # inst = MetadataConsistency()

if __name__ == '__main__':
    unittest.main()
