# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_user_metrics_response import GetUserMetricsResponse

class TestGetUserMetricsResponse(unittest.TestCase):
    """GetUserMetricsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserMetricsResponse:
        """Test GetUserMetricsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserMetricsResponse`
        """
        model = GetUserMetricsResponse()
        if include_optional:
            return GetUserMetricsResponse(
                bucket_count = 56,
                used_space = 56
            )
        else:
            return GetUserMetricsResponse(
                bucket_count = 56,
                used_space = 56,
        )
        """

    def testGetUserMetricsResponse(self):
        """Test GetUserMetricsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
