# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_update_storage_policy_request import V1UpdateStoragePolicyRequest

class TestV1UpdateStoragePolicyRequest(unittest.TestCase):
    """V1UpdateStoragePolicyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UpdateStoragePolicyRequest:
        """Test V1UpdateStoragePolicyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UpdateStoragePolicyRequest`
        """
        model = V1UpdateStoragePolicyRequest()
        if include_optional:
            return V1UpdateStoragePolicyRequest(
                policy = openapi_client.models.storage_policy.StoragePolicy(
                    replicas = [
                        openapi_client.models.replica.Replica(
                            count = 56, 
                            selector = '', )
                        ], 
                    placement_factor = 56, 
                    selectors = [
                        openapi_client.models.selector.Selector(
                            name = '', 
                            count = 56, 
                            attribute = '', 
                            filter = '', 
                            clause = [
                                'SAME'
                                ], )
                        ], 
                    filters = [
                        openapi_client.models.placement_filter.PlacementFilter(
                            name = '', 
                            key = '', 
                            op = [
                                'EQ'
                                ], 
                            value = '', 
                            filters = [
                                openapi_client.models.placement_filter.PlacementFilter(
                                    name = '', 
                                    key = '', 
                                    op = [
                                        'EQ'
                                        ], 
                                    value = '', 
                                    filters = [
                                        
                                        ], )
                                ], )
                        ], 
                    ec_rules = [
                        openapi_client.models.ec_rule.ECRule(
                            selector = '', 
                            data_parts = 56, 
                            parity_parts = 56, )
                        ], 
                    initial_placement = openapi_client.models.initial_placement_policy.InitialPlacementPolicy(
                        replica_limits = [
                            56
                            ], 
                        max_replicas = 56, 
                        prefer_local = True, ), ),
                consistency = 'strict',
                default = True
            )
        else:
            return V1UpdateStoragePolicyRequest(
                policy = openapi_client.models.storage_policy.StoragePolicy(
                    replicas = [
                        openapi_client.models.replica.Replica(
                            count = 56, 
                            selector = '', )
                        ], 
                    placement_factor = 56, 
                    selectors = [
                        openapi_client.models.selector.Selector(
                            name = '', 
                            count = 56, 
                            attribute = '', 
                            filter = '', 
                            clause = [
                                'SAME'
                                ], )
                        ], 
                    filters = [
                        openapi_client.models.placement_filter.PlacementFilter(
                            name = '', 
                            key = '', 
                            op = [
                                'EQ'
                                ], 
                            value = '', 
                            filters = [
                                openapi_client.models.placement_filter.PlacementFilter(
                                    name = '', 
                                    key = '', 
                                    op = [
                                        'EQ'
                                        ], 
                                    value = '', 
                                    filters = [
                                        
                                        ], )
                                ], )
                        ], 
                    ec_rules = [
                        openapi_client.models.ec_rule.ECRule(
                            selector = '', 
                            data_parts = 56, 
                            parity_parts = 56, )
                        ], 
                    initial_placement = openapi_client.models.initial_placement_policy.InitialPlacementPolicy(
                        replica_limits = [
                            56
                            ], 
                        max_replicas = 56, 
                        prefer_local = True, ), ),
        )
        """

    def testV1UpdateStoragePolicyRequest(self):
        """Test V1UpdateStoragePolicyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
