# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.token_type import TokenType

class TestTokenType(unittest.TestCase):
    """TokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenType(self):
        """Test TokenType"""
        # inst = TokenType()

if __name__ == '__main__':
    unittest.main()
