# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_metrics_response import GetMetricsResponse

class TestGetMetricsResponse(unittest.TestCase):
    """GetMetricsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMetricsResponse:
        """Test GetMetricsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMetricsResponse`
        """
        model = GetMetricsResponse()
        if include_optional:
            return GetMetricsResponse(
                buckets = 0,
                objects = 0,
                data_size = 0,
                nodes = [
                    openapi_client.models.metrics_node.MetricsNode(
                        endpoint = '', 
                        uptime = 0, 
                        drives = [
                            openapi_client.models.metrics_drive.MetricsDrive(
                                mount_point = '', 
                                total_space = 0, 
                                used_space = 0, 
                                avail_space = 0, )
                            ], )
                    ]
            )
        else:
            return GetMetricsResponse(
                buckets = 0,
                objects = 0,
                data_size = 0,
                nodes = [
                    openapi_client.models.metrics_node.MetricsNode(
                        endpoint = '', 
                        uptime = 0, 
                        drives = [
                            openapi_client.models.metrics_drive.MetricsDrive(
                                mount_point = '', 
                                total_space = 0, 
                                used_space = 0, 
                                avail_space = 0, )
                            ], )
                    ],
        )
        """

    def testGetMetricsResponse(self):
        """Test GetMetricsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
