# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_s3_create_access_token_request import V1S3CreateAccessTokenRequest

class TestV1S3CreateAccessTokenRequest(unittest.TestCase):
    """V1S3CreateAccessTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1S3CreateAccessTokenRequest:
        """Test V1S3CreateAccessTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1S3CreateAccessTokenRequest`
        """
        model = V1S3CreateAccessTokenRequest()
        if include_optional:
            return V1S3CreateAccessTokenRequest(
                ttl = '30 days.',
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                read_content = True,
                read_headers = True,
                create = True,
                delete = True,
                container_name = '',
                token_name = ''
            )
        else:
            return V1S3CreateAccessTokenRequest(
                token_name = '',
        )
        """

    def testV1S3CreateAccessTokenRequest(self):
        """Test V1S3CreateAccessTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
