# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_namespace_response import GetNamespaceResponse

class TestGetNamespaceResponse(unittest.TestCase):
    """GetNamespaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNamespaceResponse:
        """Test GetNamespaceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNamespaceResponse`
        """
        model = GetNamespaceResponse()
        if include_optional:
            return GetNamespaceResponse(
                name = 'my-namespace',
                description = 'accounting production data and service accounts'
            )
        else:
            return GetNamespaceResponse(
                name = 'my-namespace',
        )
        """

    def testGetNamespaceResponse(self):
        """Test GetNamespaceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
