# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.storage_node_address import StorageNodeAddress

class TestStorageNodeAddress(unittest.TestCase):
    """StorageNodeAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StorageNodeAddress:
        """Test StorageNodeAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageNodeAddress`
        """
        model = StorageNodeAddress()
        if include_optional:
            return StorageNodeAddress(
                address = 'Nhfg3TbpwogLvDGVvAvqyThbsHgoSUKwtn'
            )
        else:
            return StorageNodeAddress(
                address = 'Nhfg3TbpwogLvDGVvAvqyThbsHgoSUKwtn',
        )
        """

    def testStorageNodeAddress(self):
        """Test StorageNodeAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
