# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_cluster_list_saml_providers_response import V1ClusterListSAMLProvidersResponse

class TestV1ClusterListSAMLProvidersResponse(unittest.TestCase):
    """V1ClusterListSAMLProvidersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClusterListSAMLProvidersResponse:
        """Test V1ClusterListSAMLProvidersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClusterListSAMLProvidersResponse`
        """
        model = V1ClusterListSAMLProvidersResponse()
        if include_optional:
            return V1ClusterListSAMLProvidersResponse(
                providers = [
                    openapi_client.models.saml_provider_record.SAMLProviderRecord(
                        id = '', 
                        label = '', )
                    ]
            )
        else:
            return V1ClusterListSAMLProvidersResponse(
                providers = [
                    openapi_client.models.saml_provider_record.SAMLProviderRecord(
                        id = '', 
                        label = '', )
                    ],
        )
        """

    def testV1ClusterListSAMLProvidersResponse(self):
        """Test V1ClusterListSAMLProvidersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
