# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.match_type import MatchType

class TestMatchType(unittest.TestCase):
    """MatchType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchType(self):
        """Test MatchType"""
        # inst = MatchType()

if __name__ == '__main__':
    unittest.main()
