# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.session_verb import SessionVerb

class TestSessionVerb(unittest.TestCase):
    """SessionVerb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionVerb(self):
        """Test SessionVerb"""
        # inst = SessionVerb()

if __name__ == '__main__':
    unittest.main()
