# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.common_detailed_token_info import CommonDetailedTokenInfo

class TestCommonDetailedTokenInfo(unittest.TestCase):
    """CommonDetailedTokenInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonDetailedTokenInfo:
        """Test CommonDetailedTokenInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonDetailedTokenInfo`
        """
        model = CommonDetailedTokenInfo()
        if include_optional:
            return CommonDetailedTokenInfo(
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                expires_at = '2022-11-21T07:12:42.686806470Z',
                created_at = '2022-11-21T07:12:42.686806470Z',
                name = '',
                bucket_name = ''
            )
        else:
            return CommonDetailedTokenInfo(
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                expires_at = '2022-11-21T07:12:42.686806470Z',
                created_at = '2022-11-21T07:12:42.686806470Z',
                name = '',
                bucket_name = '',
        )
        """

    def testCommonDetailedTokenInfo(self):
        """Test CommonDetailedTokenInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
