# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_initial_registration_request import V1InitialRegistrationRequest

class TestV1InitialRegistrationRequest(unittest.TestCase):
    """V1InitialRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1InitialRegistrationRequest:
        """Test V1InitialRegistrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1InitialRegistrationRequest`
        """
        model = V1InitialRegistrationRequest()
        if include_optional:
            return V1InitialRegistrationRequest(
                login = '',
                password = ''
            )
        else:
            return V1InitialRegistrationRequest(
                login = '',
                password = '',
        )
        """

    def testV1InitialRegistrationRequest(self):
        """Test V1InitialRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
