# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_match import SearchMatch

class TestSearchMatch(unittest.TestCase):
    """SearchMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchMatch(self):
        """Test SearchMatch"""
        # inst = SearchMatch()

if __name__ == '__main__':
    unittest.main()
