# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_cluster_saml_provider_info import V1ClusterSAMLProviderInfo

class TestV1ClusterSAMLProviderInfo(unittest.TestCase):
    """V1ClusterSAMLProviderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClusterSAMLProviderInfo:
        """Test V1ClusterSAMLProviderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClusterSAMLProviderInfo`
        """
        model = V1ClusterSAMLProviderInfo()
        if include_optional:
            return V1ClusterSAMLProviderInfo(
                label = '',
                entity_id = '',
                idp_metadata = '',
                root_url = 'https://morphbits.io/',
                metadata_path = '/api/v1/saml/abc123/metadata. Where `abc123` is a provider `id`.',
                acs_path = '/api/v1/saml/abc123/acs. Where `abc123` is a provider `id`.',
                slo_path = '/api/v1/saml/abc123/slo. Where `abc123` is a provider `id`.',
                domains = ["@morphbits.io","@example.com"]
            )
        else:
            return V1ClusterSAMLProviderInfo(
                label = '',
                entity_id = '',
                idp_metadata = '',
                root_url = 'https://morphbits.io/',
                metadata_path = '/api/v1/saml/abc123/metadata. Where `abc123` is a provider `id`.',
                acs_path = '/api/v1/saml/abc123/acs. Where `abc123` is a provider `id`.',
        )
        """

    def testV1ClusterSAMLProviderInfo(self):
        """Test V1ClusterSAMLProviderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
