# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.placement_policy import PlacementPolicy

class TestPlacementPolicy(unittest.TestCase):
    """PlacementPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlacementPolicy:
        """Test PlacementPolicy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlacementPolicy`
        """
        model = PlacementPolicy()
        if include_optional:
            return PlacementPolicy(
                replicas = [
                    openapi_client.models.replica.Replica(
                        count = 56, 
                        selector = '', )
                    ],
                container_backup_factor = 56,
                selectors = [
                    openapi_client.models.selector.Selector(
                        name = '', 
                        count = 56, 
                        attribute = '', 
                        filter = '', 
                        clause = [
                            'SAME'
                            ], )
                    ],
                filters = [
                    openapi_client.models.placement_filter.PlacementFilter(
                        name = '', 
                        key = '', 
                        op = [
                            'EQ'
                            ], 
                        value = '', 
                        filters = [
                            openapi_client.models.placement_filter.PlacementFilter(
                                name = '', 
                                key = '', 
                                op = [
                                    'EQ'
                                    ], 
                                value = '', 
                                filters = [
                                    
                                    ], )
                            ], )
                    ]
            )
        else:
            return PlacementPolicy(
                replicas = [
                    openapi_client.models.replica.Replica(
                        count = 56, 
                        selector = '', )
                    ],
                container_backup_factor = 56,
                selectors = [
                    openapi_client.models.selector.Selector(
                        name = '', 
                        count = 56, 
                        attribute = '', 
                        filter = '', 
                        clause = [
                            'SAME'
                            ], )
                    ],
                filters = [
                    openapi_client.models.placement_filter.PlacementFilter(
                        name = '', 
                        key = '', 
                        op = [
                            'EQ'
                            ], 
                        value = '', 
                        filters = [
                            openapi_client.models.placement_filter.PlacementFilter(
                                name = '', 
                                key = '', 
                                op = [
                                    'EQ'
                                    ], 
                                value = '', 
                                filters = [
                                    
                                    ], )
                            ], )
                    ],
        )
        """

    def testPlacementPolicy(self):
        """Test PlacementPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
