# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.user_management_delete_request import UserManagementDeleteRequest

class TestUserManagementDeleteRequest(unittest.TestCase):
    """UserManagementDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserManagementDeleteRequest:
        """Test UserManagementDeleteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserManagementDeleteRequest`
        """
        model = UserManagementDeleteRequest()
        if include_optional:
            return UserManagementDeleteRequest(
                super_key = ''
            )
        else:
            return UserManagementDeleteRequest(
        )
        """

    def testUserManagementDeleteRequest(self):
        """Test UserManagementDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
