# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.s3_token_info import S3TokenInfo

class TestS3TokenInfo(unittest.TestCase):
    """S3TokenInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3TokenInfo:
        """Test S3TokenInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3TokenInfo`
        """
        model = S3TokenInfo()
        if include_optional:
            return S3TokenInfo(
                id = '',
                name = ''
            )
        else:
            return S3TokenInfo(
                id = '',
                name = '',
        )
        """

    def testS3TokenInfo(self):
        """Test S3TokenInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
