# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.s3_create_access_token_response import S3CreateAccessTokenResponse

class TestS3CreateAccessTokenResponse(unittest.TestCase):
    """S3CreateAccessTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3CreateAccessTokenResponse:
        """Test S3CreateAccessTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3CreateAccessTokenResponse`
        """
        model = S3CreateAccessTokenResponse()
        if include_optional:
            return S3CreateAccessTokenResponse(
                access_key_id = '',
                secret_access_key = ''
            )
        else:
            return S3CreateAccessTokenResponse(
                access_key_id = '',
                secret_access_key = '',
        )
        """

    def testS3CreateAccessTokenResponse(self):
        """Test S3CreateAccessTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
