# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_default_storage_quota_response import GetDefaultStorageQuotaResponse

class TestGetDefaultStorageQuotaResponse(unittest.TestCase):
    """GetDefaultStorageQuotaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDefaultStorageQuotaResponse:
        """Test GetDefaultStorageQuotaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDefaultStorageQuotaResponse`
        """
        model = GetDefaultStorageQuotaResponse()
        if include_optional:
            return GetDefaultStorageQuotaResponse(
                default_quota = 56
            )
        else:
            return GetDefaultStorageQuotaResponse(
                default_quota = 56,
        )
        """

    def testGetDefaultStorageQuotaResponse(self):
        """Test GetDefaultStorageQuotaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
