# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.set_storage_quota_request import SetStorageQuotaRequest

class TestSetStorageQuotaRequest(unittest.TestCase):
    """SetStorageQuotaRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetStorageQuotaRequest:
        """Test SetStorageQuotaRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetStorageQuotaRequest`
        """
        model = SetStorageQuotaRequest()
        if include_optional:
            return SetStorageQuotaRequest(
                soft_quota = 56,
                hard_quota = 56
            )
        else:
            return SetStorageQuotaRequest(
                soft_quota = 56,
                hard_quota = 56,
        )
        """

    def testSetStorageQuotaRequest(self):
        """Test SetStorageQuotaRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
