# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_update_user_request import V1UpdateUserRequest

class TestV1UpdateUserRequest(unittest.TestCase):
    """V1UpdateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UpdateUserRequest:
        """Test V1UpdateUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UpdateUserRequest`
        """
        model = V1UpdateUserRequest()
        if include_optional:
            return V1UpdateUserRequest(
                role = 'user',
                password = ''
            )
        else:
            return V1UpdateUserRequest(
                role = 'user',
                password = '',
        )
        """

    def testV1UpdateUserRequest(self):
        """Test V1UpdateUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
