# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bucket_transfer import BucketTransfer

class TestBucketTransfer(unittest.TestCase):
    """BucketTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BucketTransfer:
        """Test BucketTransfer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BucketTransfer`
        """
        model = BucketTransfer()
        if include_optional:
            return BucketTransfer(
                id = '2b5b6d2c-44b5-4b92-8a1f-3b8a03d69c2a',
                bucket = 'my-bucket',
                sender_login = 'sender',
                recipient_login = 'recipient'
            )
        else:
            return BucketTransfer(
                id = '2b5b6d2c-44b5-4b92-8a1f-3b8a03d69c2a',
                bucket = 'my-bucket',
                sender_login = 'sender',
                recipient_login = 'recipient',
        )
        """

    def testBucketTransfer(self):
        """Test BucketTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
