# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.replica import Replica

class TestReplica(unittest.TestCase):
    """Replica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Replica:
        """Test Replica
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Replica`
        """
        model = Replica()
        if include_optional:
            return Replica(
                count = 56,
                selector = ''
            )
        else:
            return Replica(
                count = 56,
                selector = '',
        )
        """

    def testReplica(self):
        """Test Replica"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
