# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_get_user_response import V1GetUserResponse

class TestV1GetUserResponse(unittest.TestCase):
    """V1GetUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GetUserResponse:
        """Test V1GetUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GetUserResponse`
        """
        model = V1GetUserResponse()
        if include_optional:
            return V1GetUserResponse(
                storage_limit = 56,
                role = 'user'
            )
        else:
            return V1GetUserResponse(
                storage_limit = 56,
                role = 'user',
        )
        """

    def testV1GetUserResponse(self):
        """Test V1GetUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
