# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.clause import Clause

class TestClause(unittest.TestCase):
    """Clause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClause(self):
        """Test Clause"""
        # inst = Clause()

if __name__ == '__main__':
    unittest.main()
