# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_objects_response import SearchObjectsResponse

class TestSearchObjectsResponse(unittest.TestCase):
    """SearchObjectsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchObjectsResponse:
        """Test SearchObjectsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchObjectsResponse`
        """
        model = SearchObjectsResponse()
        if include_optional:
            return SearchObjectsResponse(
                objects = [
                    {"objectId":"8N3o7Dtr6T1xteCt6eRwhpmJ7JhME58Hyu1dvaswuTDd","attributes":{"filePath":"/my/object/name.txt"}}
                    ],
                cursor = '',
                incomplete = True
            )
        else:
            return SearchObjectsResponse(
                objects = [
                    {"objectId":"8N3o7Dtr6T1xteCt6eRwhpmJ7JhME58Hyu1dvaswuTDd","attributes":{"filePath":"/my/object/name.txt"}}
                    ],
        )
        """

    def testSearchObjectsResponse(self):
        """Test SearchObjectsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
