# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.detailed_bearer_token_info import DetailedBearerTokenInfo

class TestDetailedBearerTokenInfo(unittest.TestCase):
    """DetailedBearerTokenInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedBearerTokenInfo:
        """Test DetailedBearerTokenInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedBearerTokenInfo`
        """
        model = DetailedBearerTokenInfo()
        if include_optional:
            return DetailedBearerTokenInfo(
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                expires_at = '2022-11-21T07:12:42.686806470Z',
                created_at = '2022-11-21T07:12:42.686806470Z',
                name = '',
                bucket_name = '',
                read_content = True,
                read_headers = True,
                create = True,
                delete = True,
                register_user = True,
                update_user = True,
                delete_user = True,
                list_user = True,
                set_user_quota = True,
                set_default_storage_quota = True,
                get_user_policies = True,
                create_user_policy = True,
                update_user_policy = True,
                get_user_policy = True,
                delete_user_policy = True,
                create_system_policy = True,
                update_system_policy = True,
                delete_system_policy = True,
                s3_get_tokens = True,
                s3_create_token = True,
                s3_token_details = True,
                s3_revoke_token = True,
                get_bearer_tokens = True,
                create_bearer_token = True,
                bearer_token_details = True,
                revoke_bearer_token = True,
                create_o_auth_provider = True,
                update_o_auth_provider = True,
                delete_o_auth_provider = True,
                upload_license = True,
                get_license = True,
                get_ir_public_keys = True,
                get_user_metrics = True,
                create_saml_provider = True,
                update_saml_provider = True,
                delete_saml_provider = True,
                list_bucket_transfers = True,
                create_namespace = True,
                get_namespace = True,
                list_namespaces = True,
                delete_namespace = True
            )
        else:
            return DetailedBearerTokenInfo(
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                expires_at = '2022-11-21T07:12:42.686806470Z',
                created_at = '2022-11-21T07:12:42.686806470Z',
                name = '',
                bucket_name = '',
                read_content = True,
                read_headers = True,
                create = True,
                delete = True,
                register_user = True,
                update_user = True,
                delete_user = True,
                list_user = True,
                set_user_quota = True,
                set_default_storage_quota = True,
                get_user_policies = True,
                create_user_policy = True,
                update_user_policy = True,
                get_user_policy = True,
                delete_user_policy = True,
                create_system_policy = True,
                update_system_policy = True,
                delete_system_policy = True,
                s3_get_tokens = True,
                s3_create_token = True,
                s3_token_details = True,
                s3_revoke_token = True,
                get_bearer_tokens = True,
                create_bearer_token = True,
                bearer_token_details = True,
                revoke_bearer_token = True,
                create_o_auth_provider = True,
                update_o_auth_provider = True,
                delete_o_auth_provider = True,
                upload_license = True,
                get_license = True,
                get_ir_public_keys = True,
                get_user_metrics = True,
                create_saml_provider = True,
                update_saml_provider = True,
                delete_saml_provider = True,
                list_bucket_transfers = True,
                create_namespace = True,
                get_namespace = True,
                list_namespaces = True,
                delete_namespace = True,
        )
        """

    def testDetailedBearerTokenInfo(self):
        """Test DetailedBearerTokenInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
