# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_bearer_token_response import CreateBearerTokenResponse

class TestCreateBearerTokenResponse(unittest.TestCase):
    """CreateBearerTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBearerTokenResponse:
        """Test CreateBearerTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBearerTokenResponse`
        """
        model = CreateBearerTokenResponse()
        if include_optional:
            return CreateBearerTokenResponse(
                token = ''
            )
        else:
            return CreateBearerTokenResponse(
                token = '',
        )
        """

    def testCreateBearerTokenResponse(self):
        """Test CreateBearerTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
