# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.metrics_node import MetricsNode

class TestMetricsNode(unittest.TestCase):
    """MetricsNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricsNode:
        """Test MetricsNode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricsNode`
        """
        model = MetricsNode()
        if include_optional:
            return MetricsNode(
                endpoint = '',
                uptime = 0,
                drives = [
                    openapi_client.models.metrics_drive.MetricsDrive(
                        mount_point = '', 
                        total_space = 0, 
                        used_space = 0, 
                        avail_space = 0, )
                    ]
            )
        else:
            return MetricsNode(
                endpoint = '',
                uptime = 0,
                drives = [
                    openapi_client.models.metrics_drive.MetricsDrive(
                        mount_point = '', 
                        total_space = 0, 
                        used_space = 0, 
                        avail_space = 0, )
                    ],
        )
        """

    def testMetricsNode(self):
        """Test MetricsNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
