# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.s3_create_access_token_request import S3CreateAccessTokenRequest

class TestS3CreateAccessTokenRequest(unittest.TestCase):
    """S3CreateAccessTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3CreateAccessTokenRequest:
        """Test S3CreateAccessTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3CreateAccessTokenRequest`
        """
        model = S3CreateAccessTokenRequest()
        if include_optional:
            return S3CreateAccessTokenRequest(
                ttl = '30 days.',
                create_bucket = True,
                delete_bucket = True,
                set_bucket_eacl = True,
                bucket_name = '',
                token_name = '',
                read = True,
                modify = True,
                manage_settings = True
            )
        else:
            return S3CreateAccessTokenRequest(
                token_name = '',
        )
        """

    def testS3CreateAccessTokenRequest(self):
        """Test S3CreateAccessTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
