# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.placement_filter import PlacementFilter

class TestPlacementFilter(unittest.TestCase):
    """PlacementFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlacementFilter:
        """Test PlacementFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlacementFilter`
        """
        model = PlacementFilter()
        if include_optional:
            return PlacementFilter(
                name = '',
                key = '',
                op = [
                    'EQ'
                    ],
                value = '',
                filters = [
                    openapi_client.models.placement_filter.PlacementFilter(
                        name = '', 
                        key = '', 
                        op = [
                            'EQ'
                            ], 
                        value = '', 
                        filters = [
                            openapi_client.models.placement_filter.PlacementFilter(
                                name = '', 
                                key = '', 
                                op = [
                                    'EQ'
                                    ], 
                                value = '', 
                                filters = , )
                            ], )
                    ]
            )
        else:
            return PlacementFilter(
                name = '',
                key = '',
                op = [
                    'EQ'
                    ],
                value = '',
                filters = [
                    openapi_client.models.placement_filter.PlacementFilter(
                        name = '', 
                        key = '', 
                        op = [
                            'EQ'
                            ], 
                        value = '', 
                        filters = [
                            openapi_client.models.placement_filter.PlacementFilter(
                                name = '', 
                                key = '', 
                                op = [
                                    'EQ'
                                    ], 
                                value = '', 
                                filters = , )
                            ], )
                    ],
        )
        """

    def testPlacementFilter(self):
        """Test PlacementFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
