# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.operation_type import OperationType

class TestOperationType(unittest.TestCase):
    """OperationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationType(self):
        """Test OperationType"""
        # inst = OperationType()

if __name__ == '__main__':
    unittest.main()
