# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_objects import SearchObjects

class TestSearchObjects(unittest.TestCase):
    """SearchObjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchObjects:
        """Test SearchObjects
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchObjects`
        """
        model = SearchObjects()
        if include_optional:
            return SearchObjects(
                object_id = '8N3o7Dtr6T1xteCt6eRwhpmJ7JhME58Hyu1dvaswuTDd',
                attributes = { }
            )
        else:
            return SearchObjects(
                object_id = '8N3o7Dtr6T1xteCt6eRwhpmJ7JhME58Hyu1dvaswuTDd',
                attributes = { },
        )
        """

    def testSearchObjects(self):
        """Test SearchObjects"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
