# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_bucket(self) -> None:
        """Test case for create_bucket

        """
        pass

    def test_create_object(self) -> None:
        """Test case for create_object

        """
        pass

    def test_create_session(self) -> None:
        """Test case for create_session

        """
        pass

    def test_delete_bucket(self) -> None:
        """Test case for delete_bucket

        """
        pass

    def test_delete_object(self) -> None:
        """Test case for delete_object

        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        """
        pass

    def test_download_object_data(self) -> None:
        """Test case for download_object_data

        """
        pass

    def test_get_bucket(self) -> None:
        """Test case for get_bucket

        """
        pass

    def test_get_metrics(self) -> None:
        """Test case for get_metrics

        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        """
        pass

    def test_get_user_list(self) -> None:
        """Test case for get_user_list

        """
        pass

    def test_list_buckets(self) -> None:
        """Test case for list_buckets

        """
        pass

    def test_list_objects(self) -> None:
        """Test case for list_objects

        """
        pass

    def test_object_metadata(self) -> None:
        """Test case for object_metadata

        """
        pass

    def test_save_user(self) -> None:
        """Test case for save_user

        """
        pass

    def test_set_eacl(self) -> None:
        """Test case for set_eacl

        """
        pass

    def test_store_session(self) -> None:
        """Test case for store_session

        """
        pass

    def test_top_up_storage_node(self) -> None:
        """Test case for top_up_storage_node

        """
        pass


if __name__ == '__main__':
    unittest.main()
