# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_cluster_create_o_auth_provider_request import V1ClusterCreateOAuthProviderRequest

class TestV1ClusterCreateOAuthProviderRequest(unittest.TestCase):
    """V1ClusterCreateOAuthProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClusterCreateOAuthProviderRequest:
        """Test V1ClusterCreateOAuthProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClusterCreateOAuthProviderRequest`
        """
        model = V1ClusterCreateOAuthProviderRequest()
        if include_optional:
            return V1ClusterCreateOAuthProviderRequest(
                label = '',
                type = 'general',
                client_id = '',
                client_secret = '',
                user_info_url = '',
                authorize_url = '',
                token_url = '',
                scope = [
                    ''
                    ],
                authorize_header_prefix = 'OAuth',
                email_path = [
                    ''
                    ],
                domains = ["@morphbits.io","@example.com"],
                use_pkce = True,
                callback_url = ''
            )
        else:
            return V1ClusterCreateOAuthProviderRequest(
                label = '',
                type = 'general',
                client_id = '',
                client_secret = '',
                user_info_url = '',
                authorize_url = '',
                token_url = '',
                scope = [
                    ''
                    ],
                authorize_header_prefix = 'OAuth',
                email_path = [
                    ''
                    ],
                domains = ["@morphbits.io","@example.com"],
                use_pkce = True,
                callback_url = '',
        )
        """

    def testV1ClusterCreateOAuthProviderRequest(self):
        """Test V1ClusterCreateOAuthProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
