# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.s3_get_access_tokens_response import S3GetAccessTokensResponse

class TestS3GetAccessTokensResponse(unittest.TestCase):
    """S3GetAccessTokensResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3GetAccessTokensResponse:
        """Test S3GetAccessTokensResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3GetAccessTokensResponse`
        """
        model = S3GetAccessTokensResponse()
        if include_optional:
            return S3GetAccessTokensResponse(
                tokens = [
                    openapi_client.models.s3_token_info.S3TokenInfo(
                        id = '', 
                        name = '', )
                    ]
            )
        else:
            return S3GetAccessTokensResponse(
                tokens = [
                    openapi_client.models.s3_token_info.S3TokenInfo(
                        id = '', 
                        name = '', )
                    ],
        )
        """

    def testS3GetAccessTokensResponse(self):
        """Test S3GetAccessTokensResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
