# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_response import LicenseResponse

class TestLicenseResponse(unittest.TestCase):
    """LicenseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseResponse:
        """Test LicenseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseResponse`
        """
        model = LicenseResponse()
        if include_optional:
            return LicenseResponse(
                node_limit = 56,
                capacity = 56,
                valid_from = '2022-11-21T07:12:42.686806470Z',
                valid_until = '2022-11-21T07:12:42.686806470Z'
            )
        else:
            return LicenseResponse(
                node_limit = 56,
                capacity = 56,
                valid_from = '2022-11-21T07:12:42.686806470Z',
                valid_until = '2022-11-21T07:12:42.686806470Z',
        )
        """

    def testLicenseResponse(self):
        """Test LicenseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
