# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_register_user_request import V1RegisterUserRequest

class TestV1RegisterUserRequest(unittest.TestCase):
    """V1RegisterUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RegisterUserRequest:
        """Test V1RegisterUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RegisterUserRequest`
        """
        model = V1RegisterUserRequest()
        if include_optional:
            return V1RegisterUserRequest(
                role = 'user',
                password = ''
            )
        else:
            return V1RegisterUserRequest(
                role = 'user',
                password = '',
        )
        """

    def testV1RegisterUserRequest(self):
        """Test V1RegisterUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
