# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_login_response import V1LoginResponse

class TestV1LoginResponse(unittest.TestCase):
    """V1LoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LoginResponse:
        """Test V1LoginResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LoginResponse`
        """
        model = V1LoginResponse()
        if include_optional:
            return V1LoginResponse(
                token = '',
                role = 'user'
            )
        else:
            return V1LoginResponse(
                token = '',
                role = 'user',
        )
        """

    def testV1LoginResponse(self):
        """Test V1LoginResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
