# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.initial_placement_policy import InitialPlacementPolicy

class TestInitialPlacementPolicy(unittest.TestCase):
    """InitialPlacementPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InitialPlacementPolicy:
        """Test InitialPlacementPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InitialPlacementPolicy`
        """
        model = InitialPlacementPolicy()
        if include_optional:
            return InitialPlacementPolicy(
                replica_limits = [
                    56
                    ],
                max_replicas = 56,
                prefer_local = True
            )
        else:
            return InitialPlacementPolicy(
        )
        """

    def testInitialPlacementPolicy(self):
        """Test InitialPlacementPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
