# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_cluster_get_o_auth_providers_response import V1ClusterGetOAuthProvidersResponse

class TestV1ClusterGetOAuthProvidersResponse(unittest.TestCase):
    """V1ClusterGetOAuthProvidersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClusterGetOAuthProvidersResponse:
        """Test V1ClusterGetOAuthProvidersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClusterGetOAuthProvidersResponse`
        """
        model = V1ClusterGetOAuthProvidersResponse()
        if include_optional:
            return V1ClusterGetOAuthProvidersResponse(
                providers = [
                    openapi_client.models.o_auth_provider_record.OAuthProviderRecord(
                        id = '', 
                        label = '', 
                        type = 'general', )
                    ]
            )
        else:
            return V1ClusterGetOAuthProvidersResponse(
                providers = [
                    openapi_client.models.o_auth_provider_record.OAuthProviderRecord(
                        id = '', 
                        label = '', 
                        type = 'general', )
                    ],
        )
        """

    def testV1ClusterGetOAuthProvidersResponse(self):
        """Test V1ClusterGetOAuthProvidersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
