# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.list_buckets_response import ListBucketsResponse

class TestListBucketsResponse(unittest.TestCase):
    """ListBucketsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBucketsResponse:
        """Test ListBucketsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBucketsResponse`
        """
        model = ListBucketsResponse()
        if include_optional:
            return ListBucketsResponse(
                buckets = [
                    ''
                    ]
            )
        else:
            return ListBucketsResponse(
                buckets = [
                    ''
                    ],
        )
        """

    def testListBucketsResponse(self):
        """Test ListBucketsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
