# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.basic_acl import BasicACL
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateBucketRequest(BaseModel):
    """
    CreateBucketRequest
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Bucket name.")
    placement_policy_name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Placement policy name.", alias="placementPolicyName")
    basic_acl: BasicACL = Field(alias="basicACL")
    lock_hours: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Optional parameter to set the period in hours during which the bucket cannot be deleted from the time of its creation. This period can be extended, but there is no way to make it expire earlier.", alias="lockHours")
    __properties: ClassVar[List[str]] = ["name", "placementPolicyName", "basicACL", "lockHours"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateBucketRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of basic_acl
        if self.basic_acl:
            _dict['basicACL'] = self.basic_acl.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateBucketRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "placementPolicyName": obj.get("placementPolicyName"),
            "basicACL": BasicACL.from_dict(obj["basicACL"]) if obj.get("basicACL") is not None else None,
            "lockHours": obj.get("lockHours")
        })
        return _obj


