# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DetailedBearerTokenInfo(BaseModel):
    """
    DetailedBearerTokenInfo
    """ # noqa: E501
    create_bucket: StrictBool = Field(description="When set to true, this token grants permission to create buckets. Note that this option enables `setBucketEacl` as well.", alias="createBucket")
    delete_bucket: StrictBool = Field(description="When set to true, this token grants permission to delete buckets.", alias="deleteBucket")
    set_bucket_eacl: StrictBool = Field(description="When set to true, this token grants permission to set buckets EACLs.", alias="setBucketEACL")
    expires_at: datetime = Field(description="Estimated time when token will expire in RFC 3339 format.", alias="expiresAt")
    created_at: datetime = Field(description="Time when token was issued in RFC 3339 format.", alias="createdAt")
    name: StrictStr = Field(description="User-defined token name.")
    bucket_name: StrictStr = Field(description="When set to non empty value, it restricts the token to function exclusively within this bucket. Note, if you set this option, you cannot create a bucket, even if `createBucket` is set to true.", alias="bucketName")
    read_content: StrictBool = Field(description="When set to true, this token grants permission to read objects.", alias="readContent")
    read_headers: StrictBool = Field(description="When set to true, this token grants permission to read objects headers.", alias="readHeaders")
    create: StrictBool = Field(description="When set to true, this token grants permission to create objects.")
    delete: StrictBool = Field(description="When set to true, this token grants permission to delete objects.")
    register_user: StrictBool = Field(description="When set to true, this token grants permission to register a new user. This option is available to admins only.", alias="registerUser")
    update_user: StrictBool = Field(description="When set to true, this token grants permission to update an existing user. This option is available to admins only.", alias="updateUser")
    delete_user: StrictBool = Field(description="When set to true, this token grants permission to delete an existing user. This option is available to admins only.", alias="deleteUser")
    list_user: StrictBool = Field(description="When set to true, this token grants permission to list users. This option is available to admins only.", alias="listUser")
    set_user_quota: StrictBool = Field(description="When set to true, this token grants permission to set user storage quota. This option is available to admins only.", alias="setUserQuota")
    set_default_storage_quota: StrictBool = Field(description="When set to true, this token grants permission to set default storage quota. This option is available to admins only.", alias="setDefaultStorageQuota")
    get_user_policies: StrictBool = Field(description="When set to true, this token grants permission to get user storage policies.", alias="getUserPolicies")
    create_user_policy: StrictBool = Field(description="When set to true, this token grants permission to create user storage policy.", alias="createUserPolicy")
    update_user_policy: StrictBool = Field(description="When set to true, this token grants permission to update user storage policy.", alias="updateUserPolicy")
    get_user_policy: StrictBool = Field(description="When set to true, this token grants permission to get user storage policy.", alias="getUserPolicy")
    delete_user_policy: StrictBool = Field(description="When set to true, this token grants permission to delete user storage policy.", alias="deleteUserPolicy")
    create_system_policy: StrictBool = Field(description="When set to true, this token grants permission to create system storage policy. This option is available to admins only.", alias="createSystemPolicy")
    update_system_policy: StrictBool = Field(description="When set to true, this token grants permission to update system storage policy. This option is available to admins only.", alias="updateSystemPolicy")
    delete_system_policy: StrictBool = Field(description="When set to true, this token grants permission to delete system storage policy. This option is available to admins only.", alias="deleteSystemPolicy")
    s3_get_tokens: StrictBool = Field(description="When set to true, this token grants permission to get S3 access tokens.", alias="s3GetTokens")
    s3_create_token: StrictBool = Field(description="When set to true, this token grants permission to create S3 access token.", alias="s3CreateToken")
    s3_token_details: StrictBool = Field(description="When set to true, this token grants permission to get S3 access token details.", alias="s3TokenDetails")
    s3_revoke_token: StrictBool = Field(description="When set to true, this token grants permission to revoke S3 access token.", alias="s3RevokeToken")
    get_bearer_tokens: StrictBool = Field(description="When set to true, this token grants permission to get Bearer tokens.", alias="getBearerTokens")
    create_bearer_token: StrictBool = Field(description="When set to true, this token grants permission to create Bearer token.", alias="createBearerToken")
    bearer_token_details: StrictBool = Field(description="When set to true, this token grants permission to get Bearer token details.", alias="bearerTokenDetails")
    revoke_bearer_token: StrictBool = Field(description="When set to true, this token grants permission to revoke Bearer token.", alias="revokeBearerToken")
    create_o_auth_provider: StrictBool = Field(description="When set to true, this token grants permission to create OAuth provider.", alias="createOAuthProvider")
    update_o_auth_provider: StrictBool = Field(description="When set to true, this token grants permission to update OAuth provider.", alias="updateOAuthProvider")
    delete_o_auth_provider: StrictBool = Field(description="When set to true, this token grants permission to delete OAuth provider.", alias="deleteOAuthProvider")
    upload_license: StrictBool = Field(description="When set to true, this token grants permission to upload license. This option is available to admins only.", alias="uploadLicense")
    get_license: StrictBool = Field(description="When set to true, this token grants permission to get license metadata. This option is available to admins only.", alias="getLicense")
    get_ir_public_keys: StrictBool = Field(description="When set to true, this token grants permission to get IR public keys. This option is available to admins only.", alias="getIRPublicKeys")
    get_user_metrics: StrictBool = Field(description="When set to true, this token grants permission to get user metrics. This option is available to admins only.", alias="getUserMetrics")
    create_saml_provider: StrictBool = Field(description="When set to true, this token grants permission to create SAML provider.", alias="createSAMLProvider")
    update_saml_provider: StrictBool = Field(description="When set to true, this token grants permission to update SAML provider.", alias="updateSAMLProvider")
    delete_saml_provider: StrictBool = Field(description="When set to true, this token grants permission to delete SAML provider.", alias="deleteSAMLProvider")
    list_bucket_transfers: StrictBool = Field(description="When set to true, this token grants permission to list user bucket transfers.", alias="listBucketTransfers")
    create_namespace: StrictBool = Field(description="When set to true, this token grants permission to create namespace. This option is available to admins only.", alias="createNamespace")
    get_namespace: StrictBool = Field(description="When set to true, this token grants permission to get namespace. This option is available to admins only.", alias="getNamespace")
    list_namespaces: StrictBool = Field(description="When set to true, this token grants permission to list namespaces. This option is available to admins only.", alias="listNamespaces")
    delete_namespace: StrictBool = Field(description="When set to true, this token grants permission to delete namespace. This option is available to admins only.", alias="deleteNamespace")
    __properties: ClassVar[List[str]] = ["createBucket", "deleteBucket", "setBucketEACL", "expiresAt", "createdAt", "name", "bucketName", "readContent", "readHeaders", "create", "delete", "registerUser", "updateUser", "deleteUser", "listUser", "setUserQuota", "setDefaultStorageQuota", "getUserPolicies", "createUserPolicy", "updateUserPolicy", "getUserPolicy", "deleteUserPolicy", "createSystemPolicy", "updateSystemPolicy", "deleteSystemPolicy", "s3GetTokens", "s3CreateToken", "s3TokenDetails", "s3RevokeToken", "getBearerTokens", "createBearerToken", "bearerTokenDetails", "revokeBearerToken", "createOAuthProvider", "updateOAuthProvider", "deleteOAuthProvider", "uploadLicense", "getLicense", "getIRPublicKeys", "getUserMetrics", "createSAMLProvider", "updateSAMLProvider", "deleteSAMLProvider", "listBucketTransfers", "createNamespace", "getNamespace", "listNamespaces", "deleteNamespace"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DetailedBearerTokenInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DetailedBearerTokenInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createBucket": obj.get("createBucket") if obj.get("createBucket") is not None else True,
            "deleteBucket": obj.get("deleteBucket") if obj.get("deleteBucket") is not None else True,
            "setBucketEACL": obj.get("setBucketEACL") if obj.get("setBucketEACL") is not None else True,
            "expiresAt": obj.get("expiresAt"),
            "createdAt": obj.get("createdAt"),
            "name": obj.get("name"),
            "bucketName": obj.get("bucketName"),
            "readContent": obj.get("readContent"),
            "readHeaders": obj.get("readHeaders"),
            "create": obj.get("create"),
            "delete": obj.get("delete"),
            "registerUser": obj.get("registerUser") if obj.get("registerUser") is not None else False,
            "updateUser": obj.get("updateUser") if obj.get("updateUser") is not None else False,
            "deleteUser": obj.get("deleteUser") if obj.get("deleteUser") is not None else False,
            "listUser": obj.get("listUser") if obj.get("listUser") is not None else False,
            "setUserQuota": obj.get("setUserQuota") if obj.get("setUserQuota") is not None else False,
            "setDefaultStorageQuota": obj.get("setDefaultStorageQuota") if obj.get("setDefaultStorageQuota") is not None else False,
            "getUserPolicies": obj.get("getUserPolicies") if obj.get("getUserPolicies") is not None else False,
            "createUserPolicy": obj.get("createUserPolicy") if obj.get("createUserPolicy") is not None else False,
            "updateUserPolicy": obj.get("updateUserPolicy") if obj.get("updateUserPolicy") is not None else False,
            "getUserPolicy": obj.get("getUserPolicy") if obj.get("getUserPolicy") is not None else False,
            "deleteUserPolicy": obj.get("deleteUserPolicy") if obj.get("deleteUserPolicy") is not None else False,
            "createSystemPolicy": obj.get("createSystemPolicy") if obj.get("createSystemPolicy") is not None else False,
            "updateSystemPolicy": obj.get("updateSystemPolicy") if obj.get("updateSystemPolicy") is not None else False,
            "deleteSystemPolicy": obj.get("deleteSystemPolicy") if obj.get("deleteSystemPolicy") is not None else False,
            "s3GetTokens": obj.get("s3GetTokens") if obj.get("s3GetTokens") is not None else False,
            "s3CreateToken": obj.get("s3CreateToken") if obj.get("s3CreateToken") is not None else False,
            "s3TokenDetails": obj.get("s3TokenDetails") if obj.get("s3TokenDetails") is not None else False,
            "s3RevokeToken": obj.get("s3RevokeToken") if obj.get("s3RevokeToken") is not None else False,
            "getBearerTokens": obj.get("getBearerTokens") if obj.get("getBearerTokens") is not None else False,
            "createBearerToken": obj.get("createBearerToken") if obj.get("createBearerToken") is not None else False,
            "bearerTokenDetails": obj.get("bearerTokenDetails") if obj.get("bearerTokenDetails") is not None else False,
            "revokeBearerToken": obj.get("revokeBearerToken") if obj.get("revokeBearerToken") is not None else False,
            "createOAuthProvider": obj.get("createOAuthProvider") if obj.get("createOAuthProvider") is not None else False,
            "updateOAuthProvider": obj.get("updateOAuthProvider") if obj.get("updateOAuthProvider") is not None else False,
            "deleteOAuthProvider": obj.get("deleteOAuthProvider") if obj.get("deleteOAuthProvider") is not None else False,
            "uploadLicense": obj.get("uploadLicense") if obj.get("uploadLicense") is not None else False,
            "getLicense": obj.get("getLicense") if obj.get("getLicense") is not None else False,
            "getIRPublicKeys": obj.get("getIRPublicKeys") if obj.get("getIRPublicKeys") is not None else False,
            "getUserMetrics": obj.get("getUserMetrics") if obj.get("getUserMetrics") is not None else False,
            "createSAMLProvider": obj.get("createSAMLProvider") if obj.get("createSAMLProvider") is not None else False,
            "updateSAMLProvider": obj.get("updateSAMLProvider") if obj.get("updateSAMLProvider") is not None else False,
            "deleteSAMLProvider": obj.get("deleteSAMLProvider") if obj.get("deleteSAMLProvider") is not None else False,
            "listBucketTransfers": obj.get("listBucketTransfers") if obj.get("listBucketTransfers") is not None else False,
            "createNamespace": obj.get("createNamespace") if obj.get("createNamespace") is not None else False,
            "getNamespace": obj.get("getNamespace") if obj.get("getNamespace") is not None else False,
            "listNamespaces": obj.get("listNamespaces") if obj.get("listNamespaces") is not None else False,
            "deleteNamespace": obj.get("deleteNamespace") if obj.get("deleteNamespace") is not None else False
        })
        return _obj


