# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from pydantic import Field
from typing_extensions import Annotated
from openapi_client.models.metrics_node import MetricsNode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetMetricsResponse(BaseModel):
    """
    GetMetricsResponse
    """ # noqa: E501
    buckets: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of buckets in the system.")
    objects: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of objects in all buckets in the system.")
    data_size: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total amount of object data stored in the system (excl. metadata).", alias="dataSize")
    nodes: List[MetricsNode] = Field(description="Listing of nodes' metrics.")
    __properties: ClassVar[List[str]] = ["buckets", "objects", "dataSize", "nodes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item in self.nodes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nodes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "buckets": obj.get("buckets"),
            "objects": obj.get("objects"),
            "dataSize": obj.get("dataSize"),
            "nodes": [MetricsNode.from_dict(_item) for _item in obj.get("nodes")] if obj.get("nodes") is not None else None
        })
        return _obj


