# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InitialPlacementPolicy(BaseModel):
    """
    Controls how objects are placed initially before the full policy is applied.
    """ # noqa: E501
    replica_limits: Optional[List[StrictInt]] = Field(default=None, description="Sets replica counts for each REP and EC rule. If used with maxReplicas sets the maximum number of replicas for each rule.", alias="replicaLimits")
    max_replicas: Optional[StrictInt] = Field(default=None, description="Sets max number of object replicas and EC partitions. Zero value means following `replicaLimits` with no additional constraint for overall replica count.", alias="maxReplicas")
    prefer_local: Optional[StrictBool] = Field(default=None, description="Indicates preference for local (as per node processing the request) storage placement.", alias="preferLocal")
    __properties: ClassVar[List[str]] = ["replicaLimits", "maxReplicas", "preferLocal"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InitialPlacementPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InitialPlacementPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replicaLimits": obj.get("replicaLimits"),
            "maxReplicas": obj.get("maxReplicas"),
            "preferLocal": obj.get("preferLocal")
        })
        return _obj


