# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_client.models.placement_filter import PlacementFilter
from openapi_client.models.replica import Replica
from openapi_client.models.selector import Selector
from typing import Optional, Set
from typing_extensions import Self

class PlacementPolicy(BaseModel):
    """
    Set of rules to select a subset of nodes from `NetworkMap` able to store container's objects.
    """ # noqa: E501
    replicas: List[Replica] = Field(description="Rules to set number of object replicas and place each one into a named bucket. MUST NOT be empty.")
    container_backup_factor: StrictInt = Field(description="Container backup factor controls how deep NeoFS will search for nodes alternatives to include into container's nodes subset.", alias="containerBackupFactor")
    selectors: List[Selector] = Field(description="Set of Selectors to form the container's nodes subset.")
    filters: List[PlacementFilter] = Field(description="List of named filters to reference in selectors.")
    __properties: ClassVar[List[str]] = ["replicas", "containerBackupFactor", "selectors", "filters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlacementPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in replicas (list)
        _items = []
        if self.replicas:
            for _item in self.replicas:
                if _item:
                    _items.append(_item.to_dict())
            _dict['replicas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in selectors (list)
        _items = []
        if self.selectors:
            for _item in self.selectors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['selectors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item in self.filters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['filters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlacementPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replicas": [Replica.from_dict(_item) for _item in obj["replicas"]] if obj.get("replicas") is not None else None,
            "containerBackupFactor": obj.get("containerBackupFactor"),
            "selectors": [Selector.from_dict(_item) for _item in obj["selectors"]] if obj.get("selectors") is not None else None,
            "filters": [PlacementFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None
        })
        return _obj


