# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from pydantic import Field
from openapi_client.models.header_type import HeaderType
from openapi_client.models.match_type import MatchType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RecordFilter(BaseModel):
    """
    RecordFilter
    """ # noqa: E501
    header_type: List[HeaderType] = Field(description="Define if Object or Request header will be used.", alias="headerType")
    match_type: List[MatchType] = Field(description="Match operation type.", alias="matchType")
    key: StrictStr = Field(description="Name of the Header to use.")
    value: StrictStr = Field(description="Expected Header Value or pattern to match.")
    __properties: ClassVar[List[str]] = ["headerType", "matchType", "key", "value"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RecordFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RecordFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "headerType": obj.get("headerType"),
            "matchType": obj.get("matchType"),
            "key": obj.get("key"),
            "value": obj.get("value")
        })
        return _obj


