# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class S3DetailedTokenInfo(BaseModel):
    """
    S3DetailedTokenInfo
    """ # noqa: E501
    create_bucket: StrictBool = Field(description="When set to true, this token grants permission to create buckets. Note that this option enables `setBucketEacl` as well.", alias="createBucket")
    delete_bucket: StrictBool = Field(description="When set to true, this token grants permission to delete buckets.", alias="deleteBucket")
    set_bucket_eacl: StrictBool = Field(description="When set to true, this token grants permission to set buckets EACLs.", alias="setBucketEACL")
    expires_at: datetime = Field(description="Estimated time when token will expire in RFC 3339 format.", alias="expiresAt")
    created_at: datetime = Field(description="Time when token was issued in RFC 3339 format.", alias="createdAt")
    name: StrictStr = Field(description="User-defined token name.")
    bucket_name: StrictStr = Field(description="When set to non empty value, it restricts the token to function exclusively within this bucket. Note, if you set this option, you cannot create a bucket, even if `createBucket` is set to true.", alias="bucketName")
    read: StrictBool = Field(description="Flag allowing to read objects with this token.")
    modify: StrictBool = Field(description="Flag allowing to create and delete objects with this token.")
    manage_settings: StrictBool = Field(description="Flag allowing to manage S3 bucket cors, tags, notifications, policy, ownerships and locks with this token.", alias="manageSettings")
    __properties: ClassVar[List[str]] = ["createBucket", "deleteBucket", "setBucketEACL", "expiresAt", "createdAt", "name", "bucketName", "read", "modify", "manageSettings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of S3DetailedTokenInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of S3DetailedTokenInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createBucket": obj.get("createBucket") if obj.get("createBucket") is not None else True,
            "deleteBucket": obj.get("deleteBucket") if obj.get("deleteBucket") is not None else True,
            "setBucketEACL": obj.get("setBucketEACL") if obj.get("setBucketEACL") is not None else True,
            "expiresAt": obj.get("expiresAt"),
            "createdAt": obj.get("createdAt"),
            "name": obj.get("name"),
            "bucketName": obj.get("bucketName"),
            "read": obj.get("read") if obj.get("read") is not None else True,
            "modify": obj.get("modify") if obj.get("modify") is not None else True,
            "manageSettings": obj.get("manageSettings") if obj.get("manageSettings") is not None else True
        })
        return _obj


