# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.search_filter import SearchFilter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchObjectsRequest(BaseModel):
    """
    List of parameters for the search request.
    """ # noqa: E501
    filters: Optional[Annotated[List[SearchFilter], Field(max_length=7)]] = Field(default=None, description="Optional list of up to 7 object filters. If it is not specified, all objects are  returned.  Special filter keys starting with \"$Object:\" can be used to filter by system attributes. The expected value formats are:    \"$Object:payloadLength\" – payload size in bytes, as a decimal uint64 string.    \"$Object:ownerID\"       – object creator identifier, as a user ID string.    \"$Object:payloadHash\"   – SHA-256 hash of the payload, as a standard Base64-encoded                              string (decoded length must be 32 bytes).    \"$Object:creationEpoch\" – object creation epoch, as a decimal uint64 string.    Other keys starting from \"$Object:*\" lead to a 400 error.  Other keys are treated as user-defined object attributes (for example \"FilePath\"). ")
    attributes: Optional[Annotated[List[StrictStr], Field(max_length=7)]] = Field(default=None, description="Optional list of attributes to be returned for each object. It must contain up to 7  attributes.   Basic object metadata can be retrieved by requesting the attributes:  \"FilePath\", \"Content-Type\", \"Timestamp\" as the creation date, and \"ExpHours\" as the  object expiration time. You also may request reserved attributes:  \"$Object:payloadLength\", \"$Object:ownerID\", \"$Object:payloadHash\", \"$Object:creationEpoch\". However, any other values starting from \"$Object:*\" will result in a 400 error.  If this parameter is empty, no attributes will be returned, only object IDs. ")
    __properties: ClassVar[List[str]] = ["filters", "attributes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchObjectsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchObjectsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filters": [SearchFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "attributes": obj.get("attributes")
        })
        return _obj


