# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.ec_rule import ECRule
from openapi_client.models.initial_placement_policy import InitialPlacementPolicy
from openapi_client.models.placement_filter import PlacementFilter
from openapi_client.models.replica import Replica
from openapi_client.models.selector import Selector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StoragePolicy(BaseModel):
    """
    Set of rules to select a subset of nodes from `NetworkMap` able to store bucket's objects. A policy must use either ecRules or replicas.
    """ # noqa: E501
    replicas: List[Replica] = Field(description="Rules to set number of object replicas and place each one into a named bucket.")
    placement_factor: StrictInt = Field(description="Bucket placement factor defines the maximum number of storage nodes (replicas×factor) that will store bucket data.", alias="placementFactor")
    selectors: Annotated[List[Selector], Field(max_length=256)] = Field(description="Set of Selectors to form the bucket's nodes subset.")
    filters: List[PlacementFilter] = Field(description="List of named filters to reference in selectors.")
    ec_rules: Optional[Annotated[List[ECRule], Field(max_length=4)]] = Field(default=None, description="List of erasure coding rules for the container.", alias="ecRules")
    initial_placement: Optional[InitialPlacementPolicy] = Field(default=None, alias="initialPlacement")
    __properties: ClassVar[List[str]] = ["replicas", "placementFactor", "selectors", "filters", "ecRules", "initialPlacement"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoragePolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in replicas (list)
        _items = []
        if self.replicas:
            for _item_replicas in self.replicas:
                if _item_replicas:
                    _items.append(_item_replicas.to_dict())
            _dict['replicas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in selectors (list)
        _items = []
        if self.selectors:
            for _item_selectors in self.selectors:
                if _item_selectors:
                    _items.append(_item_selectors.to_dict())
            _dict['selectors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ec_rules (list)
        _items = []
        if self.ec_rules:
            for _item_ec_rules in self.ec_rules:
                if _item_ec_rules:
                    _items.append(_item_ec_rules.to_dict())
            _dict['ecRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of initial_placement
        if self.initial_placement:
            _dict['initialPlacement'] = self.initial_placement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoragePolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replicas": [Replica.from_dict(_item) for _item in obj["replicas"]] if obj.get("replicas") is not None else None,
            "placementFactor": obj.get("placementFactor"),
            "selectors": [Selector.from_dict(_item) for _item in obj["selectors"]] if obj.get("selectors") is not None else None,
            "filters": [PlacementFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "ecRules": [ECRule.from_dict(_item) for _item in obj["ecRules"]] if obj.get("ecRules") is not None else None,
            "initialPlacement": InitialPlacementPolicy.from_dict(obj["initialPlacement"]) if obj.get("initialPlacement") is not None else None
        })
        return _obj


