# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TokenType(str, Enum):
    """
    Token type. The `session` type is used in user login session tokens and for login via an OAuth provider; the `pat` (Personal Access Token) type is for external apps/services.
    """

    """
    allowed enum values
    """
    SESSION = 'session'
    PAT = 'pat'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TokenType from a JSON string"""
        return cls(json.loads(json_str))


