# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.o_auth_provider_type import OAuthProviderType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1ClusterCreateOAuthProviderRequest(BaseModel):
    """
    V1ClusterCreateOAuthProviderRequest
    """ # noqa: E501
    label: StrictStr = Field(description="Label for login button.")
    type: OAuthProviderType
    client_id: StrictStr = Field(description="OAuth provider application client id.", alias="clientID")
    client_secret: StrictStr = Field(description="OAuth provider application client secret.", alias="clientSecret")
    user_info_url: StrictStr = Field(description="OAuth provider URL, to get user details.", alias="userInfoURL")
    authorize_url: StrictStr = Field(description="OAuth provider URL, to authorize user.", alias="authorizeURL")
    token_url: StrictStr = Field(description="OAuth provider URL, to exchange token.", alias="tokenURL")
    scope: List[StrictStr] = Field(description="OAuth provider scope required to get user's email.")
    authorize_header_prefix: StrictStr = Field(description="OAuth provider Authorization header. It is used to get user's info from OAuth provider.", alias="authorizeHeaderPrefix")
    email_path: List[StrictStr] = Field(description="The path to extract email field from user info response.", alias="emailPath")
    domains: List[StrictStr] = Field(description="Whitelisted domains. Users from these domains allowed to login.")
    use_pkce: StrictBool = Field(description="Tells to use PKCE feature with OAuth provider. The feature must be supported by provider.", alias="usePKCE")
    callback_url: StrictStr = Field(description="The OAuth provider redirects users to this URL after authorization. It must exactly match the one configured in your OAuth provider’s dashboard.", alias="callbackURL")
    __properties: ClassVar[List[str]] = ["label", "type", "clientID", "clientSecret", "userInfoURL", "authorizeURL", "tokenURL", "scope", "authorizeHeaderPrefix", "emailPath", "domains", "usePKCE", "callbackURL"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1ClusterCreateOAuthProviderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1ClusterCreateOAuthProviderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label": obj.get("label"),
            "type": obj.get("type"),
            "clientID": obj.get("clientID"),
            "clientSecret": obj.get("clientSecret"),
            "userInfoURL": obj.get("userInfoURL"),
            "authorizeURL": obj.get("authorizeURL"),
            "tokenURL": obj.get("tokenURL"),
            "scope": obj.get("scope"),
            "authorizeHeaderPrefix": obj.get("authorizeHeaderPrefix") if obj.get("authorizeHeaderPrefix") is not None else 'OAuth',
            "emailPath": obj.get("emailPath"),
            "domains": obj.get("domains"),
            "usePKCE": obj.get("usePKCE") if obj.get("usePKCE") is not None else False,
            "callbackURL": obj.get("callbackURL")
        })
        return _obj


