# coding: utf-8

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_client.models.user_role import UserRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1GetUserResponse(BaseModel):
    """
    V1GetUserResponse
    """ # noqa: E501
    storage_hard_quota: StrictInt = Field(description="User's storage hard quota for all their buckets, in bytes. A zero value means unlimited.", alias="storageHardQuota")
    storage_soft_quota: StrictInt = Field(description="User's storage soft quota for all their buckets, in bytes. A zero value means unlimited.", alias="storageSoftQuota")
    role: UserRole
    __properties: ClassVar[List[str]] = ["storageHardQuota", "storageSoftQuota", "role"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1GetUserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1GetUserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "storageHardQuota": obj.get("storageHardQuota"),
            "storageSoftQuota": obj.get("storageSoftQuota"),
            "role": obj.get("role")
        })
        return _obj


