# coding: utf-8

# flake8: noqa

"""
    Morph API

    REST API of the multi-node/multi-drive Morph object storage.

    The version of the OpenAPI document: v0.25.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ACLGroup",
    "ActionType",
    "BaseTokenInfo",
    "BasicACL",
    "BearerTokenInfo",
    "BucketTransfer",
    "Clause",
    "CommonCreateTokenRequest",
    "CommonDetailedTokenInfo",
    "CreateBearerTokenRequest",
    "CreateBearerTokenResponse",
    "CreateBucketRequest",
    "CreateBucketTransferRequest",
    "CreateBucketTransferResponse",
    "CreateNamespaceRequest",
    "CreateObjectResponse",
    "DetailedBearerTokenInfo",
    "EACL",
    "EACLRecord",
    "ECRule",
    "GetBearerTokenDetailsResponse",
    "GetBearerTokensResponse",
    "GetBucketResponse",
    "GetEaclResponse",
    "GetMetricsResponse",
    "GetNamespaceResponse",
    "GetStorageQuotaResponse",
    "GetTimelockResponse",
    "GetUserListResponse",
    "GetUserMetricsResponse",
    "HeaderType",
    "InitialPlacementPolicy",
    "LicenseResponse",
    "ListBucketTransfersResponse",
    "ListBucketsResponse",
    "ListNamespacesResponse",
    "ListObjectsResponse",
    "MatchType",
    "MetadataConsistency",
    "MetricsDrive",
    "MetricsNode",
    "NamedStoragePolicy",
    "OAuthProviderRecord",
    "OAuthProviderType",
    "Object",
    "Operation",
    "OperationType",
    "PlacementFilter",
    "RecordFilter",
    "RecordTarget",
    "Replica",
    "Role",
    "S3CreateAccessTokenRequest",
    "S3CreateAccessTokenResponse",
    "S3DetailedTokenInfo",
    "S3GetAccessTokenDetailsResponse",
    "S3GetAccessTokensResponse",
    "S3TokenInfo",
    "SAMLProviderRecord",
    "SearchFilter",
    "SearchMatch",
    "SearchObjects",
    "SearchObjectsRequest",
    "SearchObjectsResponse",
    "Selector",
    "SetEaclRequest",
    "SetStorageQuotaRequest",
    "SetTimelockRequest",
    "StorageNodeAddress",
    "StoragePolicy",
    "TokenType",
    "User",
    "UserRole",
    "V1ClusterCreateOAuthProviderRequest",
    "V1ClusterCreateSAMLProviderRequest",
    "V1ClusterGetOAuthProvidersResponse",
    "V1ClusterListSAMLProvidersResponse",
    "V1ClusterSAMLProviderInfo",
    "V1CreateSystemStoragePolicyRequest",
    "V1CreateUserStoragePolicyRequest",
    "V1GetStoragePolicyResponse",
    "V1GetSystemStoragePoliciesResponse",
    "V1GetUserResponse",
    "V1GetUserStoragePoliciesResponse",
    "V1LoginRequest",
    "V1LoginResponse",
    "V1UpdateStoragePolicyRequest",
    "V1UpdateUserRequest",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.acl_group import ACLGroup as ACLGroup
from openapi_client.models.action_type import ActionType as ActionType
from openapi_client.models.base_token_info import BaseTokenInfo as BaseTokenInfo
from openapi_client.models.basic_acl import BasicACL as BasicACL
from openapi_client.models.bearer_token_info import BearerTokenInfo as BearerTokenInfo
from openapi_client.models.bucket_transfer import BucketTransfer as BucketTransfer
from openapi_client.models.clause import Clause as Clause
from openapi_client.models.common_create_token_request import CommonCreateTokenRequest as CommonCreateTokenRequest
from openapi_client.models.common_detailed_token_info import CommonDetailedTokenInfo as CommonDetailedTokenInfo
from openapi_client.models.create_bearer_token_request import CreateBearerTokenRequest as CreateBearerTokenRequest
from openapi_client.models.create_bearer_token_response import CreateBearerTokenResponse as CreateBearerTokenResponse
from openapi_client.models.create_bucket_request import CreateBucketRequest as CreateBucketRequest
from openapi_client.models.create_bucket_transfer_request import CreateBucketTransferRequest as CreateBucketTransferRequest
from openapi_client.models.create_bucket_transfer_response import CreateBucketTransferResponse as CreateBucketTransferResponse
from openapi_client.models.create_namespace_request import CreateNamespaceRequest as CreateNamespaceRequest
from openapi_client.models.create_object_response import CreateObjectResponse as CreateObjectResponse
from openapi_client.models.detailed_bearer_token_info import DetailedBearerTokenInfo as DetailedBearerTokenInfo
from openapi_client.models.eacl import EACL as EACL
from openapi_client.models.eacl_record import EACLRecord as EACLRecord
from openapi_client.models.ec_rule import ECRule as ECRule
from openapi_client.models.get_bearer_token_details_response import GetBearerTokenDetailsResponse as GetBearerTokenDetailsResponse
from openapi_client.models.get_bearer_tokens_response import GetBearerTokensResponse as GetBearerTokensResponse
from openapi_client.models.get_bucket_response import GetBucketResponse as GetBucketResponse
from openapi_client.models.get_eacl_response import GetEaclResponse as GetEaclResponse
from openapi_client.models.get_metrics_response import GetMetricsResponse as GetMetricsResponse
from openapi_client.models.get_namespace_response import GetNamespaceResponse as GetNamespaceResponse
from openapi_client.models.get_storage_quota_response import GetStorageQuotaResponse as GetStorageQuotaResponse
from openapi_client.models.get_timelock_response import GetTimelockResponse as GetTimelockResponse
from openapi_client.models.get_user_list_response import GetUserListResponse as GetUserListResponse
from openapi_client.models.get_user_metrics_response import GetUserMetricsResponse as GetUserMetricsResponse
from openapi_client.models.header_type import HeaderType as HeaderType
from openapi_client.models.initial_placement_policy import InitialPlacementPolicy as InitialPlacementPolicy
from openapi_client.models.license_response import LicenseResponse as LicenseResponse
from openapi_client.models.list_bucket_transfers_response import ListBucketTransfersResponse as ListBucketTransfersResponse
from openapi_client.models.list_buckets_response import ListBucketsResponse as ListBucketsResponse
from openapi_client.models.list_namespaces_response import ListNamespacesResponse as ListNamespacesResponse
from openapi_client.models.list_objects_response import ListObjectsResponse as ListObjectsResponse
from openapi_client.models.match_type import MatchType as MatchType
from openapi_client.models.metadata_consistency import MetadataConsistency as MetadataConsistency
from openapi_client.models.metrics_drive import MetricsDrive as MetricsDrive
from openapi_client.models.metrics_node import MetricsNode as MetricsNode
from openapi_client.models.named_storage_policy import NamedStoragePolicy as NamedStoragePolicy
from openapi_client.models.o_auth_provider_record import OAuthProviderRecord as OAuthProviderRecord
from openapi_client.models.o_auth_provider_type import OAuthProviderType as OAuthProviderType
from openapi_client.models.object import Object as Object
from openapi_client.models.operation import Operation as Operation
from openapi_client.models.operation_type import OperationType as OperationType
from openapi_client.models.placement_filter import PlacementFilter as PlacementFilter
from openapi_client.models.record_filter import RecordFilter as RecordFilter
from openapi_client.models.record_target import RecordTarget as RecordTarget
from openapi_client.models.replica import Replica as Replica
from openapi_client.models.role import Role as Role
from openapi_client.models.s3_create_access_token_request import S3CreateAccessTokenRequest as S3CreateAccessTokenRequest
from openapi_client.models.s3_create_access_token_response import S3CreateAccessTokenResponse as S3CreateAccessTokenResponse
from openapi_client.models.s3_detailed_token_info import S3DetailedTokenInfo as S3DetailedTokenInfo
from openapi_client.models.s3_get_access_token_details_response import S3GetAccessTokenDetailsResponse as S3GetAccessTokenDetailsResponse
from openapi_client.models.s3_get_access_tokens_response import S3GetAccessTokensResponse as S3GetAccessTokensResponse
from openapi_client.models.s3_token_info import S3TokenInfo as S3TokenInfo
from openapi_client.models.saml_provider_record import SAMLProviderRecord as SAMLProviderRecord
from openapi_client.models.search_filter import SearchFilter as SearchFilter
from openapi_client.models.search_match import SearchMatch as SearchMatch
from openapi_client.models.search_objects import SearchObjects as SearchObjects
from openapi_client.models.search_objects_request import SearchObjectsRequest as SearchObjectsRequest
from openapi_client.models.search_objects_response import SearchObjectsResponse as SearchObjectsResponse
from openapi_client.models.selector import Selector as Selector
from openapi_client.models.set_eacl_request import SetEaclRequest as SetEaclRequest
from openapi_client.models.set_storage_quota_request import SetStorageQuotaRequest as SetStorageQuotaRequest
from openapi_client.models.set_timelock_request import SetTimelockRequest as SetTimelockRequest
from openapi_client.models.storage_node_address import StorageNodeAddress as StorageNodeAddress
from openapi_client.models.storage_policy import StoragePolicy as StoragePolicy
from openapi_client.models.token_type import TokenType as TokenType
from openapi_client.models.user import User as User
from openapi_client.models.user_role import UserRole as UserRole
from openapi_client.models.v1_cluster_create_o_auth_provider_request import V1ClusterCreateOAuthProviderRequest as V1ClusterCreateOAuthProviderRequest
from openapi_client.models.v1_cluster_create_saml_provider_request import V1ClusterCreateSAMLProviderRequest as V1ClusterCreateSAMLProviderRequest
from openapi_client.models.v1_cluster_get_o_auth_providers_response import V1ClusterGetOAuthProvidersResponse as V1ClusterGetOAuthProvidersResponse
from openapi_client.models.v1_cluster_list_saml_providers_response import V1ClusterListSAMLProvidersResponse as V1ClusterListSAMLProvidersResponse
from openapi_client.models.v1_cluster_saml_provider_info import V1ClusterSAMLProviderInfo as V1ClusterSAMLProviderInfo
from openapi_client.models.v1_create_system_storage_policy_request import V1CreateSystemStoragePolicyRequest as V1CreateSystemStoragePolicyRequest
from openapi_client.models.v1_create_user_storage_policy_request import V1CreateUserStoragePolicyRequest as V1CreateUserStoragePolicyRequest
from openapi_client.models.v1_get_storage_policy_response import V1GetStoragePolicyResponse as V1GetStoragePolicyResponse
from openapi_client.models.v1_get_system_storage_policies_response import V1GetSystemStoragePoliciesResponse as V1GetSystemStoragePoliciesResponse
from openapi_client.models.v1_get_user_response import V1GetUserResponse as V1GetUserResponse
from openapi_client.models.v1_get_user_storage_policies_response import V1GetUserStoragePoliciesResponse as V1GetUserStoragePoliciesResponse
from openapi_client.models.v1_login_request import V1LoginRequest as V1LoginRequest
from openapi_client.models.v1_login_response import V1LoginResponse as V1LoginResponse
from openapi_client.models.v1_update_storage_policy_request import V1UpdateStoragePolicyRequest as V1UpdateStoragePolicyRequest
from openapi_client.models.v1_update_user_request import V1UpdateUserRequest as V1UpdateUserRequest

